version: "3"

services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app
      MYSQL_USER: app
      MYSQL_PASSWORD: app
      TZ: Asia/Tokyo
    ports:
      - 3306:3306
    volumes:
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./db/data:/var/lib/mysql
      - ./db/sql:/docker-entrypoint-initdb.d

  web:
    depends_on:
      - db
    build:
      context: web/
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./web/app:/app
      - ./web/env_files/scripts:/scripts
